name: lint
on: [push, pull_request]
jobs:
  lint:
    name: Lint Python scripts
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - run: make lint
